name: Test - Nightly

on:
  schedule:
    - cron: "0 22 * * *"

  # creates a button
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
        type: choice
        options:
          - info
          - warning
          - debug

jobs:
  test:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: |
            3.10
      - name: Run pytest
        run: |
          python -m pip install --upgrade pytest
          python -m pip install -e .
          python -m pytest
        env:
          LOG_LEVEL: ${{ github.event.inputs.logLevel }}